# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'socket_img_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SocketImgTx(object):
    def setupUi(self, SocketImgTx):
        SocketImgTx.setObjectName("SocketImgTx")
        SocketImgTx.resize(544, 588)
        self.labe_show_img = QtWidgets.QLabel(SocketImgTx)
        self.labe_show_img.setGeometry(QtCore.QRect(60, 120, 401, 431))
        self.labe_show_img.setStyleSheet("font: 12pt \"Lucida Console\";")
        self.labe_show_img.setText("")
        self.labe_show_img.setObjectName("labe_show_img")
        self.horizontalLayoutWidget = QtWidgets.QWidget(SocketImgTx)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 20, 351, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_ip_add = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_ip_add.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.lineEdit_ip_add.setObjectName("lineEdit_ip_add")
        self.horizontalLayout.addWidget(self.lineEdit_ip_add)
        self.bt_connect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_connect.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.bt_connect.setObjectName("bt_connect")
        self.horizontalLayout.addWidget(self.bt_connect)

        self.retranslateUi(SocketImgTx)
        QtCore.QMetaObject.connectSlotsByName(SocketImgTx)

    def retranslateUi(self, SocketImgTx):
        _translate = QtCore.QCoreApplication.translate
        SocketImgTx.setWindowTitle(_translate("SocketImgTx", "Form"))
        self.label.setText(_translate("SocketImgTx", "Client IP"))
        self.bt_connect.setText(_translate("SocketImgTx", "Connect"))
