# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'common_serial_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommonSerial(object):
    def setupUi(self, CommonSerial):
        CommonSerial.setObjectName("CommonSerial")
        CommonSerial.resize(803, 765)
        self.bt_back = QtWidgets.QPushButton(CommonSerial)
        self.bt_back.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.bt_back.setStyleSheet("font: 9pt \"Lucida Console\";")
        self.bt_back.setObjectName("bt_back")
        self.groupBox = QtWidgets.QGroupBox(CommonSerial)
        self.groupBox.setGeometry(QtCore.QRect(540, 20, 251, 691))
        self.groupBox.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_hex_send = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_hex_send.setObjectName("checkBox_hex_send")
        self.horizontalLayout.addWidget(self.checkBox_hex_send)
        self.checkBox_hex_receive = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_hex_receive.setObjectName("checkBox_hex_receive")
        self.horizontalLayout.addWidget(self.checkBox_hex_receive)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.bt_send_to_com = QtWidgets.QPushButton(self.groupBox)
        self.bt_send_to_com.setObjectName("bt_send_to_com")
        self.gridLayout.addWidget(self.bt_send_to_com, 2, 0, 1, 1)
        self.verticalLayout_Serial = QtWidgets.QVBoxLayout()
        self.verticalLayout_Serial.setObjectName("verticalLayout_Serial")
        self.formGroupBox = QtWidgets.QGroupBox(self.groupBox)
        self.formGroupBox.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_com_check = QtWidgets.QLabel(self.formGroupBox)
        self.label_com_check.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_com_check.setObjectName("label_com_check")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_com_check)
        self.bt_com_detect = QtWidgets.QPushButton(self.formGroupBox)
        self.bt_com_detect.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.bt_com_detect.setAutoRepeatInterval(100)
        self.bt_com_detect.setDefault(True)
        self.bt_com_detect.setObjectName("bt_com_detect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bt_com_detect)
        self.label_com_select = QtWidgets.QLabel(self.formGroupBox)
        self.label_com_select.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_com_select.setObjectName("label_com_select")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_com_select)
        self.comBox_com_select = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_com_select.setObjectName("comBox_com_select")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comBox_com_select)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.label_boud_rate = QtWidgets.QLabel(self.formGroupBox)
        self.label_boud_rate.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_boud_rate.setObjectName("label_boud_rate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_boud_rate)
        self.comBox_boud_rate = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_boud_rate.setObjectName("comBox_boud_rate")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comBox_boud_rate)
        self.label_data_bit = QtWidgets.QLabel(self.formGroupBox)
        self.label_data_bit.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_data_bit.setObjectName("label_data_bit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_data_bit)
        self.comBox_data_bit = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_data_bit.setObjectName("comBox_data_bit")
        self.comBox_data_bit.addItem("")
        self.comBox_data_bit.addItem("")
        self.comBox_data_bit.addItem("")
        self.comBox_data_bit.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comBox_data_bit)
        self.label_crc_check = QtWidgets.QLabel(self.formGroupBox)
        self.label_crc_check.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_crc_check.setObjectName("label_crc_check")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_crc_check)
        self.comBox_crc_check = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_crc_check.setObjectName("comBox_crc_check")
        self.comBox_crc_check.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comBox_crc_check)
        self.label_stop_bit = QtWidgets.QLabel(self.formGroupBox)
        self.label_stop_bit.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_stop_bit.setObjectName("label_stop_bit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_stop_bit)
        self.com_box_stop_bit = QtWidgets.QComboBox(self.formGroupBox)
        self.com_box_stop_bit.setObjectName("com_box_stop_bit")
        self.com_box_stop_bit.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.com_box_stop_bit)
        self.bt_open_com = QtWidgets.QPushButton(self.formGroupBox)
        self.bt_open_com.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    height:20px;\n"
"    border-radius:6px;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:14px;\n"
"    color:black;\n"
"    background-color:#e1e1e1\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:#eef0f6;\n"
" }\n"
" \n"
" QPushButton:pressed{\n"
"     background-color:#ffffff;\n"
"     }\n"
"")
        self.bt_open_com.setObjectName("bt_open_com")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.bt_open_com)
        self.bt_close_com = QtWidgets.QPushButton(self.formGroupBox)
        self.bt_close_com.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    height:20px;\n"
"    border-radius:6px;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:14px;\n"
"    color:black;\n"
"    background-color:#e1e1e1\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:#eef0f6;\n"
" }\n"
" \n"
" QPushButton:pressed{\n"
"     background-color:#ffffff;\n"
"     }\n"
"")
        self.bt_close_com.setObjectName("bt_close_com")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.bt_close_com)
        self.verticalLayout_Serial.addWidget(self.formGroupBox)
        self.formGroupBox_Serial = QtWidgets.QGroupBox(self.groupBox)
        self.formGroupBox_Serial.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.formGroupBox_Serial.setObjectName("formGroupBox_Serial")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox_Serial)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_have_received = QtWidgets.QLabel(self.formGroupBox_Serial)
        self.label_have_received.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_have_received.setObjectName("label_have_received")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_have_received)
        self.lineEdit_have_received = QtWidgets.QLineEdit(self.formGroupBox_Serial)
        self.lineEdit_have_received.setObjectName("lineEdit_have_received")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_have_received)
        self.label_have_tx = QtWidgets.QLabel(self.formGroupBox_Serial)
        self.label_have_tx.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_have_tx.setObjectName("label_have_tx")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_have_tx)
        self.lineEdit_have_tx = QtWidgets.QLineEdit(self.formGroupBox_Serial)
        self.lineEdit_have_tx.setObjectName("lineEdit_have_tx")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_have_tx)
        self.verticalLayout_Serial.addWidget(self.formGroupBox_Serial)
        self.gridLayout.addLayout(self.verticalLayout_Serial, 0, 0, 1, 1)
        self.textEdit_send_region = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_send_region.setObjectName("textEdit_send_region")
        self.gridLayout.addWidget(self.textEdit_send_region, 1, 0, 1, 1)
        self.textBrowser_receive_region = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_receive_region.setObjectName("textBrowser_receive_region")
        self.gridLayout.addWidget(self.textBrowser_receive_region, 4, 0, 1, 1)

        self.retranslateUi(CommonSerial)
        self.bt_back.clicked.connect(CommonSerial.close)
        QtCore.QMetaObject.connectSlotsByName(CommonSerial)

    def retranslateUi(self, CommonSerial):
        _translate = QtCore.QCoreApplication.translate
        CommonSerial.setWindowTitle(_translate("CommonSerial", "Form"))
        self.bt_back.setText(_translate("CommonSerial", "Back"))
        self.groupBox.setTitle(_translate("CommonSerial", "Serial"))
        self.checkBox_hex_send.setText(_translate("CommonSerial", "Hex Send"))
        self.checkBox_hex_receive.setText(_translate("CommonSerial", "Hex Receive"))
        self.bt_send_to_com.setText(_translate("CommonSerial", "Send"))
        self.formGroupBox.setTitle(_translate("CommonSerial", "串口设置"))
        self.label_com_check.setText(_translate("CommonSerial", "串口检测："))
        self.bt_com_detect.setText(_translate("CommonSerial", "检测串口"))
        self.label_com_select.setText(_translate("CommonSerial", "串口选择："))
        self.label_boud_rate.setText(_translate("CommonSerial", "波特率："))
        self.comBox_boud_rate.setItemText(0, _translate("CommonSerial", "115200"))
        self.comBox_boud_rate.setItemText(1, _translate("CommonSerial", "2400"))
        self.comBox_boud_rate.setItemText(2, _translate("CommonSerial", "4800"))
        self.comBox_boud_rate.setItemText(3, _translate("CommonSerial", "9600"))
        self.comBox_boud_rate.setItemText(4, _translate("CommonSerial", "14400"))
        self.comBox_boud_rate.setItemText(5, _translate("CommonSerial", "19200"))
        self.comBox_boud_rate.setItemText(6, _translate("CommonSerial", "38400"))
        self.comBox_boud_rate.setItemText(7, _translate("CommonSerial", "57600"))
        self.comBox_boud_rate.setItemText(8, _translate("CommonSerial", "76800"))
        self.comBox_boud_rate.setItemText(9, _translate("CommonSerial", "12800"))
        self.comBox_boud_rate.setItemText(10, _translate("CommonSerial", "230400"))
        self.comBox_boud_rate.setItemText(11, _translate("CommonSerial", "460800"))
        self.label_data_bit.setText(_translate("CommonSerial", "数据位："))
        self.comBox_data_bit.setItemText(0, _translate("CommonSerial", "8"))
        self.comBox_data_bit.setItemText(1, _translate("CommonSerial", "7"))
        self.comBox_data_bit.setItemText(2, _translate("CommonSerial", "6"))
        self.comBox_data_bit.setItemText(3, _translate("CommonSerial", "5"))
        self.label_crc_check.setText(_translate("CommonSerial", "校验位："))
        self.comBox_crc_check.setItemText(0, _translate("CommonSerial", "N"))
        self.label_stop_bit.setText(_translate("CommonSerial", "停止位："))
        self.com_box_stop_bit.setItemText(0, _translate("CommonSerial", "1"))
        self.bt_open_com.setText(_translate("CommonSerial", "打开串口"))
        self.bt_close_com.setText(_translate("CommonSerial", "关闭串口"))
        self.formGroupBox_Serial.setTitle(_translate("CommonSerial", "串口状态"))
        self.label_have_received.setText(_translate("CommonSerial", "已接收："))
        self.label_have_tx.setText(_translate("CommonSerial", "已发送："))
