# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmd_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CMD(object):
    def setupUi(self, CMD):
        CMD.setObjectName("CMD")
        CMD.resize(895, 726)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(CMD)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(CMD)
        self.groupBox.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_browser_cmd = QtWidgets.QTextBrowser(self.groupBox)
        self.text_browser_cmd.setObjectName("text_browser_cmd")
        self.verticalLayout_2.addWidget(self.text_browser_cmd)
        self.bt_clear = QtWidgets.QPushButton(self.groupBox)
        self.bt_clear.setObjectName("bt_clear")
        self.verticalLayout_2.addWidget(self.bt_clear)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(CMD)
        self.groupBox_2.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_back = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_back.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.bt_back.setObjectName("bt_back")
        self.verticalLayout.addWidget(self.bt_back)
        self.bt_version = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_version.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.bt_version.setObjectName("bt_version")
        self.verticalLayout.addWidget(self.bt_version)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setStyleSheet("font: 10pt \"Lucida Console\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(CMD)
        self.groupBox_3.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_hex_send = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_hex_send.setObjectName("checkBox_hex_send")
        self.horizontalLayout_2.addWidget(self.checkBox_hex_send)
        self.checkBox_hex_receive = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_hex_receive.setObjectName("checkBox_hex_receive")
        self.horizontalLayout_2.addWidget(self.checkBox_hex_receive)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.bt_send_to_com = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_send_to_com.setObjectName("bt_send_to_com")
        self.gridLayout.addWidget(self.bt_send_to_com, 2, 0, 1, 1)
        self.verticalLayout_Serial = QtWidgets.QVBoxLayout()
        self.verticalLayout_Serial.setObjectName("verticalLayout_Serial")
        self.formGroupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.formGroupBox.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_com_check = QtWidgets.QLabel(self.formGroupBox)
        self.label_com_check.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_com_check.setObjectName("label_com_check")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_com_check)
        self.bt_com_detect = QtWidgets.QPushButton(self.formGroupBox)
        self.bt_com_detect.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.bt_com_detect.setAutoRepeatInterval(100)
        self.bt_com_detect.setDefault(True)
        self.bt_com_detect.setObjectName("bt_com_detect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bt_com_detect)
        self.label_com_select = QtWidgets.QLabel(self.formGroupBox)
        self.label_com_select.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_com_select.setObjectName("label_com_select")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_com_select)
        self.comBox_com_select = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_com_select.setObjectName("comBox_com_select")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comBox_com_select)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.label_boud_rate = QtWidgets.QLabel(self.formGroupBox)
        self.label_boud_rate.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_boud_rate.setObjectName("label_boud_rate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_boud_rate)
        self.comBox_boud_rate = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_boud_rate.setObjectName("comBox_boud_rate")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.comBox_boud_rate.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comBox_boud_rate)
        self.label_data_bit = QtWidgets.QLabel(self.formGroupBox)
        self.label_data_bit.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_data_bit.setObjectName("label_data_bit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_data_bit)
        self.comBox_data_bit = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_data_bit.setObjectName("comBox_data_bit")
        self.comBox_data_bit.addItem("")
        self.comBox_data_bit.addItem("")
        self.comBox_data_bit.addItem("")
        self.comBox_data_bit.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comBox_data_bit)
        self.label_crc_check = QtWidgets.QLabel(self.formGroupBox)
        self.label_crc_check.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_crc_check.setObjectName("label_crc_check")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_crc_check)
        self.comBox_crc_check = QtWidgets.QComboBox(self.formGroupBox)
        self.comBox_crc_check.setObjectName("comBox_crc_check")
        self.comBox_crc_check.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comBox_crc_check)
        self.label_stop_bit = QtWidgets.QLabel(self.formGroupBox)
        self.label_stop_bit.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_stop_bit.setObjectName("label_stop_bit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_stop_bit)
        self.com_box_stop_bit = QtWidgets.QComboBox(self.formGroupBox)
        self.com_box_stop_bit.setObjectName("com_box_stop_bit")
        self.com_box_stop_bit.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.com_box_stop_bit)
        self.bt_open_com = QtWidgets.QPushButton(self.formGroupBox)
        self.bt_open_com.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    height:20px;\n"
"    border-radius:6px;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:14px;\n"
"    color:black;\n"
"    background-color:#e1e1e1\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:#eef0f6;\n"
" }\n"
" \n"
" QPushButton:pressed{\n"
"     background-color:#ffffff;\n"
"     }\n"
"")
        self.bt_open_com.setObjectName("bt_open_com")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.bt_open_com)
        self.bt_close_com = QtWidgets.QPushButton(self.formGroupBox)
        self.bt_close_com.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    height:20px;\n"
"    border-radius:6px;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:14px;\n"
"    color:black;\n"
"    background-color:#e1e1e1\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:#eef0f6;\n"
" }\n"
" \n"
" QPushButton:pressed{\n"
"     background-color:#ffffff;\n"
"     }\n"
"")
        self.bt_close_com.setObjectName("bt_close_com")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.bt_close_com)
        self.verticalLayout_Serial.addWidget(self.formGroupBox)
        self.formGroupBox_Serial = QtWidgets.QGroupBox(self.groupBox_3)
        self.formGroupBox_Serial.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.formGroupBox_Serial.setObjectName("formGroupBox_Serial")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox_Serial)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_have_received = QtWidgets.QLabel(self.formGroupBox_Serial)
        self.label_have_received.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_have_received.setObjectName("label_have_received")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_have_received)
        self.lineEdit_have_received = QtWidgets.QLineEdit(self.formGroupBox_Serial)
        self.lineEdit_have_received.setObjectName("lineEdit_have_received")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_have_received)
        self.label_have_tx = QtWidgets.QLabel(self.formGroupBox_Serial)
        self.label_have_tx.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.label_have_tx.setObjectName("label_have_tx")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_have_tx)
        self.lineEdit_have_tx = QtWidgets.QLineEdit(self.formGroupBox_Serial)
        self.lineEdit_have_tx.setObjectName("lineEdit_have_tx")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_have_tx)
        self.verticalLayout_Serial.addWidget(self.formGroupBox_Serial)
        self.gridLayout.addLayout(self.verticalLayout_Serial, 0, 0, 1, 1)
        self.textEdit_send_region = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_send_region.setObjectName("textEdit_send_region")
        self.gridLayout.addWidget(self.textEdit_send_region, 1, 0, 1, 1)
        self.textBrowser_receive_region = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_receive_region.setObjectName("textBrowser_receive_region")
        self.gridLayout.addWidget(self.textBrowser_receive_region, 4, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_3.setStretch(1, 1)

        self.retranslateUi(CMD)
        self.bt_clear.clicked.connect(self.text_browser_cmd.clear)
        QtCore.QMetaObject.connectSlotsByName(CMD)

    def retranslateUi(self, CMD):
        _translate = QtCore.QCoreApplication.translate
        CMD.setWindowTitle(_translate("CMD", "Form"))
        self.groupBox.setTitle(_translate("CMD", "CMD"))
        self.bt_clear.setText(_translate("CMD", "clear"))
        self.groupBox_2.setTitle(_translate("CMD", "Command"))
        self.bt_back.setText(_translate("CMD", "Back"))
        self.bt_version.setText(_translate("CMD", "version"))
        self.pushButton.setText(_translate("CMD", "Command-List"))
        self.groupBox_3.setTitle(_translate("CMD", "Serial"))
        self.checkBox_hex_send.setText(_translate("CMD", "Hex Send"))
        self.checkBox_hex_receive.setText(_translate("CMD", "Hex Receive"))
        self.bt_send_to_com.setText(_translate("CMD", "Send"))
        self.formGroupBox.setTitle(_translate("CMD", "串口设置"))
        self.label_com_check.setText(_translate("CMD", "串口检测："))
        self.bt_com_detect.setText(_translate("CMD", "检测串口"))
        self.label_com_select.setText(_translate("CMD", "串口选择："))
        self.label_boud_rate.setText(_translate("CMD", "波特率："))
        self.comBox_boud_rate.setItemText(0, _translate("CMD", "115200"))
        self.comBox_boud_rate.setItemText(1, _translate("CMD", "2400"))
        self.comBox_boud_rate.setItemText(2, _translate("CMD", "4800"))
        self.comBox_boud_rate.setItemText(3, _translate("CMD", "9600"))
        self.comBox_boud_rate.setItemText(4, _translate("CMD", "14400"))
        self.comBox_boud_rate.setItemText(5, _translate("CMD", "19200"))
        self.comBox_boud_rate.setItemText(6, _translate("CMD", "38400"))
        self.comBox_boud_rate.setItemText(7, _translate("CMD", "57600"))
        self.comBox_boud_rate.setItemText(8, _translate("CMD", "76800"))
        self.comBox_boud_rate.setItemText(9, _translate("CMD", "12800"))
        self.comBox_boud_rate.setItemText(10, _translate("CMD", "230400"))
        self.comBox_boud_rate.setItemText(11, _translate("CMD", "460800"))
        self.label_data_bit.setText(_translate("CMD", "数据位："))
        self.comBox_data_bit.setItemText(0, _translate("CMD", "8"))
        self.comBox_data_bit.setItemText(1, _translate("CMD", "7"))
        self.comBox_data_bit.setItemText(2, _translate("CMD", "6"))
        self.comBox_data_bit.setItemText(3, _translate("CMD", "5"))
        self.label_crc_check.setText(_translate("CMD", "校验位："))
        self.comBox_crc_check.setItemText(0, _translate("CMD", "N"))
        self.label_stop_bit.setText(_translate("CMD", "停止位："))
        self.com_box_stop_bit.setItemText(0, _translate("CMD", "1"))
        self.bt_open_com.setText(_translate("CMD", "打开串口"))
        self.bt_close_com.setText(_translate("CMD", "关闭串口"))
        self.formGroupBox_Serial.setTitle(_translate("CMD", "串口状态"))
        self.label_have_received.setText(_translate("CMD", "已接收："))
        self.label_have_tx.setText(_translate("CMD", "已发送："))
