# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainInterFace(object):
    def setupUi(self, MainInterFace):
        MainInterFace.setObjectName("MainInterFace")
        MainInterFace.resize(526, 571)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainInterFace)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(MainInterFace)
        self.widget.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Lucida Console\";")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_img_tx = QtWidgets.QPushButton(self.widget)
        self.bt_img_tx.setStyleSheet("font: 12pt \"Lucida Console\";")
        self.bt_img_tx.setDefault(False)
        self.bt_img_tx.setFlat(False)
        self.bt_img_tx.setObjectName("bt_img_tx")
        self.verticalLayout.addWidget(self.bt_img_tx)
        self.bt_serial = QtWidgets.QPushButton(self.widget)
        self.bt_serial.setStyleSheet("font: 12pt \"Lucida Console\";")
        self.bt_serial.setObjectName("bt_serial")
        self.verticalLayout.addWidget(self.bt_serial)
        self.bt_cmd = QtWidgets.QPushButton(self.widget)
        self.bt_cmd.setStyleSheet("font: 12pt \"Lucida Console\";")
        self.bt_cmd.setObjectName("bt_cmd")
        self.verticalLayout.addWidget(self.bt_cmd)
        self.bt_gimbal = QtWidgets.QPushButton(self.widget)
        self.bt_gimbal.setStyleSheet("font: 12pt \"Lucida Console\";")
        self.bt_gimbal.setObjectName("bt_gimbal")
        self.verticalLayout.addWidget(self.bt_gimbal)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(MainInterFace)
        QtCore.QMetaObject.connectSlotsByName(MainInterFace)

    def retranslateUi(self, MainInterFace):
        _translate = QtCore.QCoreApplication.translate
        MainInterFace.setWindowTitle(_translate("MainInterFace", "Form"))
        self.bt_img_tx.setText(_translate("MainInterFace", "Img Tx"))
        self.bt_serial.setToolTip(_translate("MainInterFace", "<html><head/><body><p>hello</p></body></html>"))
        self.bt_serial.setText(_translate("MainInterFace", "Serial"))
        self.bt_cmd.setText(_translate("MainInterFace", "Cmd"))
        self.bt_gimbal.setText(_translate("MainInterFace", "Gimbal"))
